// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://maktfitnwngxjjrtdqyn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ha3RmaXRud25neGpqcnRkcXluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg3MDcyNzQsImV4cCI6MjA5NDI4MzI3NH0.AJnAmHG7P-7hNr1PUWKcO-uQxgD5y_CeI_LbPOjccvQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});