// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://onmloxbgblyqqufgdulm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ubWxveGJnYmx5cXF1ZmdkdWxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM0MjUwNjUsImV4cCI6MjA3OTAwMTA2NX0.Atf3Dw5BMvyk5G6OfloUz_GvY8LC1owudJLDe1kNZIs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // @ts-ignore - localStorage may not be available in all environments
    storage: typeof localStorage !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});